
// RallyUsers action types
export const CHECKING_USER = "CHECKING_USER";
export const USER_FOUND = "USER_FOUND";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const LIST_USERS = "LIST_USERS";

export const LOGIN = "LOGIN"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const RETRIEVED_DATA = "RETRIEVED_DATA";
export const RETRIEVAL_FAILED = "RETRIEVAL_FAILED"

export const MEETING_CREATED = "MEETING_CREATED";
export const MEET_CREATE_FAILED = "MEET_CREATE_FAILED";