# Generated by Django 3.2.9 on 2022-01-09 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rally.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=rally.models.getMeetingTitle, max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('editable', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RallyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempfield', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=rally.models.getTaskName, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_completed', models.DateTimeField(blank=True)),
                ('deadline', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to='rally.rallyuser')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rally.meeting')),
                ('owners', models.ManyToManyField(related_name='task_owners', to='rally.RallyUser')),
                ('subscribers', models.ManyToManyField(related_name='task_subscribers', to='rally.RallyUser')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='agreed',
            field=models.ManyToManyField(related_name='meet_agreed', to='rally.RallyUser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_creator', to='rally.rallyuser'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='owners',
            field=models.ManyToManyField(related_name='meet_owners', to='rally.RallyUser'),
        ),
    ]
