# Generated by Django 3.2.9 on 2021-12-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupuser',
            name='name',
        ),
        migrations.AddField(
            model_name='signupuser',
            name='user_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
