# Generated by Django 3.2.9 on 2022-01-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rallyuser',
            old_name='tempfield',
            new_name='role',
        ),
    ]
