# Generated by Django 3.2.9 on 2021-12-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0002_auto_20211201_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupuser',
            name='user_slug',
        ),
    ]
