# Generated by Django 3.2.9 on 2021-12-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0004_signupuser_tempfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupuser',
            name='tempfield',
        ),
    ]
