# Generated by Django 3.2.9 on 2021-12-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rally', '0005_remove_signupuser_tempfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='tempfield',
            field=models.TextField(default=''),
        ),
    ]
